apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: oracle-monitor
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
