apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: oracle-monitor
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.oracle-monitor.svc.cluster.local:9092"
  API_URL: "http://api-service.oracle-monitor.svc.cluster.local:8000"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
  namespace: oracle-monitor
type: Opaque
stringData:
  SUPABASE_URL: "https://avglpohuwizutgybnmgz.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Z2xwb2h1d2l6dXRneWJubWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MTI1NjUsImV4cCI6MjA1NDM4ODU2NX0.Zv5bZPfmDTVvtLNMQQJvmxcKBLLMHHCQrJbXQdqJGKI"
  GEMINI_API_KEY: "AIzaSyDcvZIhwJwqWUvbzRCDdVWZxqWZxqWZxqW"
