apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: oracle-monitor
  name: collector-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector-role-binding
  namespace: oracle-monitor
subjects:
- kind: ServiceAccount
  name: default
  namespace: oracle-monitor
roleRef:
  kind: Role
  name: collector-role
  apiGroup: rbac.authorization.k8s.io
