apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
  namespace: oracle-monitor
type: Opaque
data:
  # Base64 encoded dummy values
  OPENAI_API_KEY: "c2stcHJvai1iYWJnSzBncWo2LTFzZHR4a3E2WEpWOU5fTzcyWGtPRGxqUWUzOWNIS2ZwZkN2YWhGdU5HdEVFakJlaXZLYkNQbjlPNlRjZjV6QVQzQmxia0ZKWUUtNHIxYy1xdWpSVzhQMVprRy1XVldfTHhvTVJJQzR6YWU3dzUxN09lQVNYRXZLeEgtX0NYX0pOb1dBVDF3eFdZVkJKNEpJQUE=" # sk-dummy-key
  DATABASE_PASSWORD: "c3VwZXJzZWNyZXQ=" # supersecret
  # Add your Supabase Service Role Key (Base64 encoded!)
  SUPABASE_SERVICE_ROLE_KEY: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1GMloyeHdiMmgxZDJsNmRYUm5lV0p1YldkNklpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMzTURFd01USXdNU3dpWlhod0lqb3lNRGcxTmpjM01qQXhmUS55ZEpSamRKNEJoSGZPWl9RcUJndHlpalhTS2xyVnBwZkJoRTJPRmQ3SmRv"
